#!/bin/sh
if [ -r /etc/default/rcS ]
then
    . /etc/default/rcS
else
    echo "/etc/default/rcS not found."
fi

case "$1" in
		start)
				echo -n "Starting staten... "
				/usr/bin/staten
				echo "done."
				;;
		stop)
				echo -n "Stopping staten... "
				pid=$(ps | awk '/[p]ython.*staten/ {print $1}')
				if [ ! -z "$pid" ]
				then
					kill $pid
				fi
				echo "done."
				;;
		restart)
				$0 stop
				sleep 1
				$0 start
				;;
		*)
				echo "usage: $0 {start|stop|restart}"
				;;
esac

