#!/bin/sh
if [ -r /etc/default/M30pump ]; then
    . /etc/default/M30pump
else
    echo "/etc/default/M30pump not found."
fi

MODULE="pump.ko"

case "$1" in
	insert)
		echo "Inserting $MODULE..."
		if [ -z "$PUMP_NAME" ]; then
			modprobe $MODULE
		else
			modprobe $MODULE pump_name=$PUMP_NAME
		fi
		echo "Inserted $MODULE"
		;;
	remove)
		echo "Removing $MODULE..."
		modprobe -r $MODULE
		echo "Removed $MODULE"
		;;
	reinsert)
		$0 remove
		$0 insert
		;;
	*)
		echo "usage: $0 {insert|remove|reinsert}"
		;;
esac

