#!/bin/sh
if [ -r /etc/default/M40board_setup ]; then
    . /etc/default/M40board_setup
else
    echo "/etc/default/M40board_setup not found."
fi

MODULE="board_setup.ko"

case "$1" in
	insert)
		echo "Inserting board_setup..."
		if [ -z "$OCB350_0_ENABLED" ]; then
			modprobe $MODULE
		else
			modprobe $MODULE ocb350_0_enabled=$OCB350_0_ENABLED
		fi
		echo "Inserted board_setup"
		;;
	remove)
		echo "Removing board_setup..."
		modprobe -r $MODULE
		echo "Removed board_setup..."
		;;
	reinsert)
		$0 remove
		$0 insert
		;;
	*)
		echo "usage: $0 {insert|remove|reinsert}"
		;;
esac

