#!/bin/sh
if [ -r /etc/default/rcS ]
then
    . /etc/default/rcS
else
    echo "/etc/default/rcS not found."
fi

MODULE="board_setup.ko"

case "$1" in
	insert)
		echo "Inserting board_setup..."
		modprobe $MODULE
		echo "Inserted board_setup"
		;;
	remove)
		echo "Removing board_setup..."
		modprobe -r $MODULE
		echo "Removed board_setup..."
		;;
	reinsert)
		$0 remove
		$0 insert
		;;
	*)
		echo "usage: $0 {insert|remove|reinsert}"
		;;
esac

