#!/bin/sh
if [ -r /etc/default/M80display ]; then
    . /etc/default/M80display
else
    echo "/etc/default/M80display not found. Using defaults."
fi
if [ -z "$FBTFT_DEVICE_NAME" ]; then
	FBTFT_DEVICE_NAME=8252md-t
fi
if [ -z "$FBTFT_DEVICE_ROTATE" ]; then
	FBTFT_DEVICE_ROTATE=0
fi


BACKLIGHT_GPIO=900

insert_backlight()
{
	echo "Exporting GPIO $BACKLIGHT_GPIO (Backlight)..."
	echo $BACKLIGHT_GPIO > /sys/class/gpio/export
	echo "Exported GPIO $BACKLIGHT_GPIO (Backlight)"
}

remove_backlight()
{
	echo "Unexporting GPIO $BACKLIGHT_GPIO (Backlight)..."
	echo $BACKLIGHT_GPIO > /sys/class/gpio/unexport
	echo "Unexported GPIO $BACKLIGHT_GPIO (Backlight)"
}


insert_8252md_t()
{
	if [ "$FBTFT_DEVICE_ROTATE" -eq 180 ]; then
		OUTPUT_CONTROL=0x72EF
	else
		OUTPUT_CONTROL=0x30EF
	fi
	INIT=-1,0x0028,0x0006,-1,0x0000,0x0001,-1,0x0010,0x0000,-1,0x0001,$OUTPUT_CONTROL,-1,0x0002,0x0600,-1,0x0003,0x6A38,-1,0x0011,0x6E70,-1,0X000F,0x0000,-1,0X000B,0x5308,-1,0x000C,0x0003,-1,0x000D,0x000A,-1,0x000E,0x2E00,-1,0x001E,0x00BE,-1,0x0025,0xA000,-1,0x0026,0x7800,-1,0x004E,0x0000,-1,0x004F,0x0000,-1,0x0012,0x08D9,-1,0x0030,0x0000,-1,0x0031,0x0104,-1,0x0032,0x0100,-1,0x0033,0x0305,-1,0x0034,0x0505,-1,0x0035,0x0305,-1,0x0036,0x0707,-1,0x0037,0x0300,-1,0x003A,0x1200,-1,0x003B,0x0800,-1,0x0007,0x0033,-1,0x0022,0x0000,-3
	echo "Inserting 8252MD-T..."
	modprobe fbtft_device.ko name=flexfb speed=50000000 gpios=reset:902,dc:901 busnum=1 cs=0 fps=60
	modprobe flexfb.ko width=320 height=240 regwidth=16 setaddrwin=2 init=$INIT
	insert_backlight
	echo "Inserted 8252MD-T"
}

remove_8252md_t()
{
	echo "Removing 8252MD-T..."
	modprobe -r fbtft_device.ko
	modprobe -r flexfb.ko
	remove_backlight
	echo "Removed 8252MD-T"
}


insert_p220md_t()
{
	echo "Inserting P220MD-T..."
	modprobe fbtft_device.ko name=p220md-t gpios=reset:902,dc:901 busnum=1 cs=0 fps=10 rotate=$FBTFT_DEVICE_ROTATE
	echo "Inserted P220MD-T"
}

remove_p220md_t()
{
	echo "Removing P220MD-T..."
	modprobe -r fbtft_device.ko
	echo "Removed P220MD-T"
}


case "$1" in
insert)
	case "$FBTFT_DEVICE_NAME" in
	8252md-t)
		insert_8252md_t
		;;
	p220md-t)
		insert_p220md_t
		;;
	*)
		echo "Invalid display name: $FBTFT_DEVICE_NAME"
		;;
	esac
	;;
remove)
	case "$FBTFT_DEVICE_NAME" in
	8252md-t)
		remove_8252md_t
		;;
	p220md-t)
		remove_p220md_t
		;;
	*)
		echo "Invalid display name: $FBTFT_DEVICE_NAME"
		;;
	esac
	;;
reinsert)
	$0 remove
	$0 insert
	;;
*)
	echo "usage: $0 {insert|remove|reinsert}"
	;;
esac

