#!/bin/sh

if [ -r /etc/default/rcK ]
then
	. /etc/default/rcK
else
    echo "/etc/default/rcK not found."
fi

/etc/init.d/Amonit stop
/etc/init.d/Adash stop
/etc/init.d/Asensord stop
/etc/init.d/S81telegraf stop
/etc/init.d/S80telegraf stop
/etc/init.d/S51rsyslog stop

# Shutdown CPU 1 and unmount
echo 0 > /sys/devices/system/cpu/cpu1/online
sleep 0.3
/bin/umount -a -r

