#!/bin/sh

if [ -r /etc/default/rcK ]
then
	. /etc/default/rcK
else
	echo "/etc/default/rcK not found."
fi

echo "rcK: gracefully stopping daemons..." > /dev/kmsg

# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
for i in $(ls -r /etc/init.d/S??*) ;do
	 # Ignore dangling symlinks (if any).
	 [ ! -f "$i" ] && continue

	case "$i" in
	*.sh)
		# Source shell script for speed.
		(
		trap - INT QUIT TSTP
		set stop
		. $i
		)
		;;
	*)
		# No sh extension, so fork subprocess.
		$i stop
		;;
	esac
done

echo "rcK: unmounting all" > /dev/kmsg

/bin/umount -a -r

echo "rcK: all done" > /dev/kmsg
