#!/bin/sh

################################################################################
# Settings from /etc/default
################################################################################
echo "rcS: [INFO] Starting"

if [ -r /etc/default/rcS ]
then
	. /etc/default/rcS
else
	echo "rcS: [INFO] /etc/default/rcS was not found and won't be used."
fi

################################################################################
# Mount all filesystems
################################################################################
echo "rcS: [INFO] Mounting filesystems"
mkdir -p /dev/pts
mount -a

################################################################################
# Determine active system partition
################################################################################
system0_version=$(awk -F= "{print \$2}" /media/system0/boot/version.txt 2> /dev/null)
system1_version=$(awk -F= "{print \$2}" /media/system1/boot/version.txt 2> /dev/null)

# Non-numbers get set to -1
if ! echo $system0_version | egrep -q '^[0-9]+$'; then
	system0_version=-1
fi
if ! echo $system1_version | egrep -q '^[0-9]+$'; then
	system1_version=-1
fi

if [ "$system0_version" -gt "$system1_version" ]; then
	active_system=/media/system0
	inactive_system=/media/system1
else
	active_system=/media/system1
	inactive_system=/media/system0
fi

# Set system partitions
ln -s $active_system /media/system
ln -s $inactive_system /media/inactive_system
echo "rcS: [INFO] active_system=$active_system"
echo "rcS: [INFO] inactive_system=$inactive_system"

################################################################################
# Overrides for the root filesystem
################################################################################
# Many of the following mounts will override existing rootfs entries.
# We make sure that we can access the rootfs version later.
mkdir -p /media/rootfs
mount --bind / /media/rootfs

### The /etc override hierarchy is as follows (uppermost mentioned first):
#
#   1. /media/config/override/etc (from the 'config' partition)
#          Nothing per default. Can be used during testing.
#
#   2. /media/config/individual/etc (from the 'config' partition)
#          Hostname, timezone, etc.
#
#   3. /etc (from the rootfs)
#          Everything from buildroot
#
mkdir -p /media/config/individual/etc
mkdir -p /media/config/override/etc
mkdir -p /media/config/workdir/etc
# Note that the lowest lowerdir (/etc) is the same as the merged dir (/etc).
# Effectively, this overrides the /etc entry with the merged version
lowerdir=/media/config/individual/etc:/etc
upperdir=/media/config/override/etc
workdir=/media/config/workdir/etc
mergeddir=/etc
options=lowerdir=$lowerdir,upperdir=$upperdir,workdir=$workdir
mount -t overlay overlay -o $options $mergeddir

### Similar for /root
mkdir -p /media/config/individual/root
mkdir -p /media/config/override/root
mkdir -p /media/config/workdir/root
# Note that the lowest lowerdir (/root) is the same as the merged dir (/root).
# Effectively, this overrides the /root entry with the merged version
lowerdir=/media/config/individual/root:/root
upperdir=/media/config/override/root
workdir=/media/config/workdir/root
mergeddir=/root
options=lowerdir=$lowerdir,upperdir=$upperdir,workdir=$workdir
mount -t overlay overlay -o $options $mergeddir


################################################################################
# Hostname
################################################################################
hostname -F /etc/hostname

################################################################################
# Time
################################################################################
# Set system time from RTC (assume its using UTC)
hwclock -us

################################################################################
# Data directories
################################################################################
mkdir -p /media/data/chrony
mkdir -p /media/data/log
mkdir -p /media/data/logrotate
mkdir -p /media/data/srv

################################################################################
# Startup scripts
################################################################################
echo "rcS: [INFO] Running all startup scripts"

# Start all init scripts in /etc/init.d executing them in numerical order.
for i in /etc/init.d/S??* ;do

	 # Ignore dangling symlinks (if any).
	 [ ! -f "$i" ] && continue

	 case "$i" in
		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set start
				. $i
			)
			;;
		*)
			# No sh extension, so fork subprocess.
			$i start
			;;
	esac
done

# Asynchronous scripts without order
for i in /etc/init.d/A* ;do

	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
		*Amonit)
			nohup sh -c "sleep 30; $i start" > /dev/null &
			;;
		*)
			nohup time sh $i start > /tmp/$(basename $i).log &
			;;
	esac
done

