#!/bin/sh
#
# Start watchdog
#

case "$1" in
 start)
		echo "Starting watchdog..."
		watchdog -t 45 /dev/watchdog
		;;
  stop)
		echo "Stopping watchdog..."
		kill $(ps | awk '/[w]atchdog -t .*/ {print $1}')
		;;
  restart|reload)
		;;
  *)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

