#!/bin/sh

if [ -r /etc/default/S40network ]
then
	. /etc/default/S40network
else
    echo "S40network: [INFO] /etc/default/S40network was not found and won't be used."
fi

case "$1" in
	start)
		echo "S40network: [INFO] Starting network"
		echo "S40network: [INFO] Bringing up 'lo'"
		ifup lo
		echo "S40network: [INFO] Bringing up 'eth0'"
		nohup ifup eth0 > /tmp/eth0.log &
        ;;

	stop)
		echo "Stopping network..."
		# Stop routing
		echo 0 > /proc/sys/net/ipv4/ip_forward
		iptables --policy INPUT   ACCEPT;
		iptables --policy OUTPUT  ACCEPT;
		iptables --policy FORWARD ACCEPT;
		iptables -Z; # zero counters
		iptables -F; # flush (delete) rules
		iptables -X; # delete all extra chains

		# Kill all daemons
		killall dnsmasq
		killall hostapd

		# Fix IP for hostname
		# TODO: FPA 02-11-2016. This does not currently work. However, there is no
		# use case for calling 'S40network stop' just yet. Fix when needed.
		# sed -i /etc/hosts -e 's/.*redpitaya/127.0.1.1\tredpitaya/'

		# Shut down all interfaces
		/sbin/ifdown -a
        ;;


	restart|reload)
		"$0" stop
		"$0" start
		;;


	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

