#!/bin/sh

if [ -r /etc/default/S40network ]
then
	. /etc/default/S40network
else
    echo "/etc/default/S40network not found."
fi

. /media/config/etc/network/config

case "$1" in
	start)
		echo "Starting network..."
		echo "++ Bringing up lo"
		ifup lo

		# Bring-up wlan0 before eth0 to avoid routing problems due to 192.168.1.100
		# default IP being assigned to eth0 if no cable is plugged in or no reply
		# is received from the DHCP server.
		# This way, even if wlan0 gets the IP in 192.168.1.x range (via DHCP), the
		# routing tables will be OK.

		echo "++ Bringing up wlan0"

		# Bring up wlan0, depending on WiFi mode: Client mode or Access Point (AP) mode
		[ "x$WIFI" == "xap" ] && {
			echo "   WiFi: Access Point (AP) mode"

			# Set-up links to proper files
			ln -sf /media/config/etc/network/interfaces.ap /etc/network/interfaces

			# Bring-up wlan0 with static (AP) config
			sleep 1; # Allow some time for the USB WiFi device to be detected.
			ifup wlan0
			WLAN_IP=`ifconfig wlan0 | grep "inet addr" | sed -e 's/.*addr://' | sed -e 's/\ .*//'`

			# Fix IP for hostname
			sed -i /etc/hosts -e 's/.*redpitaya/'$WLAN_IP'\tredpitaya/'

			# Start the AP & DHCP daemons
			echo "   WiFi: Starting AP daemon"
			hostapd -B -P /var/run/hostapd.pid /media/config/hostapd.conf > /dev/null
			echo "   WiFi: Starting DHCP & DNS server"
			dnsmasq --conf-file=/media/config/etc/network/dnsmasq.conf

		} || {
			echo "   WiFi: Client mode"

			# Set-up links to proper files
			ln -sf /media/config/etc/network/interfaces /etc/network/interfaces

			if [ -e /media/config/etc/network/wpa_supplicant.conf ]
			then
			#sleep 1; # Allow some time for the USB WiFi device to be detected.
			ifup wlan0
			fi
		}

		# 1000Base-T Ethernet
		echo "++ Bringing up eth0"
		# Built-in ethernet (DHCP)
		nohup ifup eth0 > /tmp/eth0.log &
		# Built-in ethernet (Static IP)
		nohup ifup eth0:0 > /tmp/eth0-0.log &
		# USB-ethernet adapter (DHCP)
		nohup ifup eth1 > /tmp/eth1.log &

		# Set-up NAT & routing in Wifi AP mode case
		[ "x$WIFI" == "xap" ] && {
			echo "++ Starting NAT & routing..."
			iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
			iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
			iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
			echo 1 > /proc/sys/net/ipv4/ip_forward
		}
        ;;


	stop)
		echo "Stopping network..."
		# Stop routing 
		echo 0 > /proc/sys/net/ipv4/ip_forward
		iptables --policy INPUT   ACCEPT;
		iptables --policy OUTPUT  ACCEPT;
		iptables --policy FORWARD ACCEPT;
		iptables -Z; # zero counters
		iptables -F; # flush (delete) rules
		iptables -X; # delete all extra chains

		# Kill all daemons
		killall dnsmasq
		killall hostapd

		# Fix IP for hostname
		# TODO: FPA 02-11-2016. This does not currently work. However, there is no
		# use case for calling 'S40network stop' just yet. Fix when needed.
		sed -i /etc/hosts -e 's/.*redpitaya/127.0.1.1\tredpitaya/'

		# Shut down all interfaces
		/sbin/ifdown -a
        ;;


	restart|reload)
		"$0" stop
		"$0" start
		;;


	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

